id: P009595
initial_creation_type: ocr
source_metadata:
  id: bdr:W4CZ74200
  title: སྤྱོད་འཇུག་འགྲེལ་པ་ཁག་གཉིས།
  author: ''
  volumes:
    7424daf429de425bb43943cf266e341f:
      image_group_id: I4CZ74271
      title: ''
      volume_number: 1
      total_pages: 986
      base_file: v001.txt
