id: I778E4E5E
legacy_id: P009595
ocr_import_info:
  bdrc_scan_id: W4CZ74200
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T16:37:34'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T21:01:05.633396+00:00'
last_modified: 2022-09-04 05:01:37.387967
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ74200
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ74200
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་འགྲེལ་པ་ཁག་གཉིས།
  author: རྒྱལ་མཁན་པོ་གྲགས་པ་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.6113960706116945
  ocr_word_median_confidence_index: 0.6299999952316284
quality: null
bases:
  I4CZ74271:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ74271
      total_pages: 986
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ74271.txt
    statistics:
      ocr_word_median_confidence_index: 0.6299999952316284
      ocr_word_mean_confidence_index: 0.6113960706116945
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
